// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ykxvziyvhquzhmlktdjz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlreHZ6aXl2aHF1emhtbGt0ZGp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1OTI0MjIsImV4cCI6MjA2MzE2ODQyMn0.BPM87mr6dNqce0Y0SLcxl_qcHaSKcqyJa7RrAN4jZkE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);